name: aks-test

on:
  workflow_dispatch:
    inputs:
      azure_credentials:
        description: "AZURE_CREDENTIALS"
        required: false
        default: ""

jobs:
  aks-login-on-windows:
    runs-on: windows-latest
    steps:
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ github.events.inputs.azure_credentials || secrets.AZURE_CREDENTIALS }}
