name: gcp-test

on:
  workflow_dispatch:

jobs:
  login:
    uses: ./.github/workflows/master-gcp.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      runner: elemental-e2e-ci-runner-x86-64-1
      zone: us-central1-a
