name: GCP Secrets test

on:
  workflow_dispatch:

jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout MUST come before auth
      - name: Checkout
        uses: actions/checkout@v3
#     - name: Authenticate to GCP
#       uses: google-github-actions/auth@v0
#       with:
#         credentials_json: ${{ secrets.GCP_CREDENTIALS }}
#     - name: Setup gcloud
#       uses: google-github-actions/setup-gcloud@v0
#     - name: List instances status
#       run: gcloud compute instances list
#     - name: List secrets
#       run: gcloud secrets list
      - name: test secrets existence
        env:
          GCP_CREDENTIALS: "${{ secrets.GCP_CREDENTIALS }}"
        run: echo "Test GCP credentials existence"
