name: GHA Events Test

on:
# pull_request:
  workflow_dispatch:

env:
  TAG_PR: ${{ github.event.pull_request.head.sha }}
  TAG_SHA: ${{ github.sha }}
jobs:
  test-01:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: |
          echo "TAG_PR=${TAG_PR}"
          echo "TAG_SHA=${TAG_SHA}"
