name: master-gcp

on:
  workflow_call:
    # Variables to set when calling this reusable workflow
    secrets:
      credentials:
        description: Credentials to use to connect
        required: true
    inputs:
      runner:
        description: Runner on which to execute tests
        required: true
        type: string
      zone:
        description: GCP zone to host the runner
        required: true
        type: string

jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout MUST come before auth
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.credentials }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: List instances status
        run: gcloud compute instances list
      - name: Start runner
        run: gcloud compute instances start --zone ${{ inputs.zone }} ${{ inputs.runner }}
      - name: List instances status
        run: gcloud compute instances list
      - name: Stop runner
        run: gcloud compute instances stop --zone ${{ inputs.zone }} ${{ inputs.runner }}
      - name: List instances status
        run: gcloud compute instances list
