name: populate_matrix_from_inputs

on:
# push:
#   branches: [main]
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Comma-separated list of Python versions e.g. "3.10","3.11"'
        default: '"3.11"'
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ${{ fromJSON(format('[{0}]', inputs.python_version || '"3.7","3.10"')) }}

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

