name: sshd-test

on: workflow_dispatch

jobs:
  test-on-direct-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Start sshd
        run: |
          sudo mkdir -p /run/sshd
          sudo ssh-keygen -A
          sudo /usr/sbin/sshd
          ps -efww | grep [s]shd
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
            go-version: '~1.17'
      - name: Check Go version
        run: |
          echo PATH=${PATH}
          go version
