name: Test GHA add-commit

on:
  schedule:
    - cron: 0 23 * * *
  workflow_dispatch:

jobs:
  add-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Generate tests description file
        id: readme_generator
        run: |
          # Generate checksum of current file
          FILE="tests/README.md"
          OLD_CHK=$(sha512sum ${FILE} 2>/dev/null) || true

          # Create new file
          pushd tests >/dev/null && make generate-readme && popd >/dev/null

          # Generate checksum of new file
          NEW_CHK=$(sha512sum ${FILE} 2>/dev/null) || true

          # Compare checksum and set generate value if needed
          if [[ "${NEW_CHK}" != "${OLD_CHK}" ]]; then
            echo "generate=needed" >> ${GITHUB_OUTPUT}
          fi
      - uses: EndBug/add-and-commit@v9
        if: steps.readme_generator.outputs.generate == 'needed'
        with:
          default_author: github_actions
          message: 'ci: update tests/README.md file'
          add: 'tests/README.md'
