name: Test GHA add-commit

on:
  workflow_dispatch:

jobs:
  add-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate tests description file
        id: readme_generator
        run: |
          # Generate checksum of current file
          FILE="tests/README.md"
          OLD_CHK=$(sha512sum ${FILE} 2>/dev/null) || true

          # Create new file
          pushd tests >/dev/null && make generate-readme && popd >/dev/null

          # Generate checksum of new file
          NEW_CHK=$(sha512sum ${FILE} 2>/dev/null) || true

          # Compare checksum and set generate value if needed
          [[ "${NEW_CHK}" != "${OLD_CHK}" ]] && echo "generate=needed" >> ${GITHUB_OUTPUT} || true

      - name: Push modified file
        if: steps.readme_generator.outputs.generate == 'needed'
        env:
          CI_COMMIT_AUTHOR: "github-actions"
          CI_COMMIT_EMAIL: "github-actions@users.noreply.github.com"
          CI_COMMIT_MESSAGE: "ci: update tests/README.md file"
          CI_COMMIT_FILE: "tests/README.md"
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git add ${{ env.CI_COMMIT_FILE }}
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
