name: Test to unset a GH ENV variable

on:
  workflow_dispatch:
    inputs:
      iso_to_test:
        description: ISO to test (default built one is empty)
        type: string
      test_type:
        description: Type of test to run (cli or ui)
        default: cli
        type: string
      upgrade_image:
        description: Image to use for the Elemental OS upgrade
        type: string
      upgrade_os_channel:
        description: Channel to use for the Elemental OS upgrade
        type: string

jobs:
  test-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Test to unset an ENV
        env:
          EMULATE_TPM: true
          ISO_BOOT: true
          OPERATOR_VERSION: "1.0"
        run: |
          echo -e "\nCheck ENV var *BEFORE* unset"
          echo "EMULATE_TPM=${EMULATE_TPM}"
          echo "ISO_BOOT=${ISO_BOOT}"

          # If elemental-operator is a v1.0 we should disable EMULATE_TPM
          [[ "${OPERATOR_VERSION}" == "1.0" ]] && unset EMULATE_TPM

          echo -e "\nCheck ENV var *AFTER* unset"
          echo "EMULATE_TPM=${EMULATE_TPM}"
          echo "ISO_BOOT=${ISO_BOOT}"
      - name: Test to check inputs
        env:
          EMULATE_TPM: true
        run: |
          set -x
          echo -e "\nCheck ENV var *BEFORE* unset"
          echo "EMULATE_TPM=${EMULATE_TPM}"

          if ${{ inputs.upgrade_image != '' }}      || \
             ${{ inputs.upgrade_os_channel != '' }} || \
             ${{ contains(inputs.iso_to_test, '/Stable:/') }}; then
            unset EMULATE_TPM
          fi

          echo -e "\nCheck ENV var *AFTER* an eventual unset"
          echo "EMULATE_TPM=${EMULATE_TPM}"
      - name: Upgrade node 1 (with osImage method) to latest build
        if: inputs.test_type == 'cli' && !contains(inputs.iso_to_test, '/Stable:/')
        env:
          CONTAINER_IMAGE: quay.io/costoolkit/elemental-ci:latest
          UPGRADE_TYPE: osImage
          VM_INDEX: 1
        run: |
          echo "!! Upgrade is started !!"
