name: Test build iso from simple script

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Build iso from script
        run: |
          # Just a simple run to test the build script, no need to upload the generated iso!
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/rancher/elemental/master/elemental-iso-build)"
