name: Test Get Repo Name

on:
  workflow_dispatch:

jobs:
  get-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show some variables
        run: |
          echo GH_REPOSITORY=${{ github.repository }}
          echo GH_REPOSITORY_NAME=${{ github.repository.name }}
          echo GH_EVENT_REPOSITORY_NAME=${{ github.event.repository.name }}
