name: Test Docker Buildx on MacOS

on:
  workflow_dispatch:

jobs:
  build:
    env:
      TAG: ${{ github.SHA }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
        arch: ["amd64"]
        include:
          - os: ubuntu-latest
            arch: "arm64"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Install deps (${{ matrix.os }})
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y mkisofs
      - name: Install deps (${{ matrix.os }})
        if: matrix.os == 'macos-latest'
        run: |
          brew install cdrtools
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
