name: test-env-test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      registry:
        required: false
        default: quay.io
        type: string
        description: Registry to use
      org:
        required: false
        default: costoolkit
        type: string
        description: Organization to use

env:
  DEFAULT_DOCKER_REGISTRY: quay.io
  DEFAULT_ORG: costoolkit

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ github.event.inputs.registry || DEFAULT_DOCKER_REGISTRY }}
      ORG: ${{ github.event.inputs.org || DEFAULT_ORG }}
#     REPO: ${{ env.DOCKER_REGISTRY }}/${{ env.ORG }}/os2-ci
    steps:
      - name: Check env variables
        run: |
          echo "DOCKER_REGISTRY=${{ env.DOCKER_REGISTRY }}"
          echo "ORG=${{ env.ORG }}"
          echo "REPO=${{ env.REPO }}"
