name: Test Docker Buildx on MacOS

on:
  workflow_dispatch:

jobs:
  build:
    env:
      TAG: ${{ github.SHA }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
        arch: ["amd64"]
        include:
          - os: ubuntu-latest
            arch: "arm64"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get runner OS name
        run: |
          echo "RUNNER OS: ${{ runner.os }}"
      - name: Install Docker on MacOS and start Colima
        if: runner.os == 'macOS'
        run: |
          brew install docker
          # Docker engine is no longer available because of licensing
          # Alternative Colima is part of the github macOS runner
          colima start
          # Ensure colima is configured for later user
          # echo "DOCKER_HOST=unix://$HOME/.colima/default/docker.sock" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Install deps (${{ matrix.os }})
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y mkisofs
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install cdrtools
          fi
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
