name: Token Test

on:
  workflow_dispatch

jobs:
  test-github-token:
    runs-on: ubuntu-latest
    steps:
      - name: Test GITHUB_TOKEN
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token
